# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Schema Composer for Oracle Data Modeler
description: > # this means to ignore newlines until "baseurl:"
 Oracle is a registered trademark of Oracle Corporation and/or its affiliates. All other company and product names are trademarks or registered trademarks of their respective companies.
 Schema Composer is not affiliated with Oracle Corporation.
 I’ve tried to make the information on this site as complete and as accurate as possible, but no guarantee of usefulness or fitness for a particular purpose is implied. The content is provided on an “as-is” basis. 
baseurl: "" 
twitter_username: colfitzpatrick
github_username:  colinfitzpatrick

# Build settings
markdown: kramdown
theme: minima

destination: ../docs

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
include:
  - updatecenter.xml
  - download/
